title: Yangzheng Primary School
url: https://yangzhengpri.moe.edu.sg
favicon: /images/yangzheng favicon.ico
colors:
  primary-color: "#252f6f"
  secondary-color: "#c4a034"
  media-colors:
    - title: media-color-one
      color: "#49759a"
    - title: media-color-two
      color: "#744d9f"
    - title: media-color-three
      color: "#00838f"
    - title: media-color-four
      color: "#00838f"
    - title: media-color-five
      color: "#00838f"
description: Yangzheng Primary School
permalink: none
baseurl: ""
exclude:
  - travis-script.js
  - .travis.yml
  - README.md
  - package.json
  - package-lock.json
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Gemfile
  - Gemfile.lock
include:
  - _redirects
defaults:
  - scope:
      path: ""
    values:
      layout: page
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
paginate: 12
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
staging: https://staging.d2hs37t6xklt4r.amplifyapp.com
prod: https://master.d2hs37t6xklt4r.amplifyapp.com
shareicon: /images/Yangzheng Pri.jpg
is_government: false
facebook-pixel: ""
google_analytics: ""
linkedin-insights: ""
